{
  fetchFromGitHub,
  buildGo126Module,
  runCommand,
  cacert,
  lib,
  bun,
  nodejs,
  bun2nix,
}:

let
  version = "unstable-2026-06-08";

  src = fetchFromGitHub {
    owner = "wesm";
    repo = "middleman";
    rev = "33a08abec398ee22e1aa9005dfabd2a5da4d4408";
    hash = "sha256-f0ZJ4b+oBpNunKFstxQCJygdSMd61UE29c8RvQ/Osvk=";
  };

  patchedSrc = runCommand "middleman-src-with-bun-nix" { } ''
    cp -r ${src} $out
    chmod -R +w $out
    cp ${./bun.nix} $out/bun.nix
  '';

  # pre-fetch bun dependencies using the generated bun.nix
  bunDeps = bun2nix.fetchBunDeps {
    bunNix = "${patchedSrc}/bun.nix"; # generated by running `bun2nix` against the lockfile
  };
in
buildGo126Module {
  pname = "middleman";

  inherit src version;

  vendorHash = "sha256-jp9aKSPh01ZEEIK9NU2P5uubhbG5mfXx/CPMeOzX4dA=";

  nativeBuildInputs = [
    bun
    nodejs
    cacert
  ];

  preBuild = ''
    # Set up bun cache from pre-fetched deps (what bun2nix.hook would do)
    export BUN_INSTALL_CACHE_DIR=$(mktemp -d)
    cp -r ${bunDeps}/share/bun-cache/. "$BUN_INSTALL_CACHE_DIR"
    export HOME=$(mktemp -d)

    # Vite+ needs a real CA bundle in this Nix build environment.
    export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt

    # Install node_modules from cache (no network needed)
    bun install --frozen-lockfile --ignore-scripts

    # Build frontend
    cd frontend && bun run build && cd ..

    # Copy into embed directory
    rm -rf internal/web/dist
    mkdir -p internal/web
    cp -r frontend/dist internal/web/dist
    printf 'ok\n' > internal/web/dist/stub.html
  '';

  subPackages = [ "cmd/middleman" ];
  buildFlags = [ "-trimpath" ];

  ldflags = [
    "-s"
    "-w"
    "-X main.version=${version}"
    "-X main.commit=${src.rev}"
    "-X main.buildDate=1970-01-01T00:00:00Z"
  ];

  meta = with lib; {
    description = "Local-first GitHub dashboard for maintainers to triage, review, and merge PRs and issues across repos";
    homepage = "https://github.com/wesm/middleman";
    license = licenses.mit;
    mainProgram = "middleman";
  };
}
