{
  fetchFromGitHub,
  buildGo126Module,
  runCommand,
  cacert,
  lib,
  bun,
  nodejs,
  bun2nix,
}:

let
  version = "unstable-2026-08-10";

  src = fetchFromGitHub {
    owner = "kenn-io";
    repo = "forge";
    rev = "1e5b31e055e1d669677686639a73ef6fd6ca5535";
    hash = "sha256-3Q+PzBkOOm4rhd4cAm9wR0Zu9itlrndk1VMy967ILXA=";
  };

  patchedSrc = runCommand "kenn-forge-src-with-bun-nix" { } ''
    cp -r ${src} $out
    chmod -R +w $out
    cp ${./bun.nix} $out/bun.nix
  '';

  # pre-fetch bun dependencies using the generated bun.nix
  bunDeps = bun2nix.fetchBunDeps {
    bunNix = "${patchedSrc}/bun.nix"; # generated by running `bun2nix` against the lockfile
  };
in
buildGo126Module {
  pname = "kenn-forge";

  inherit src version;

  vendorHash = "sha256-OQ+1IBzxQAMcmhgFknoeUjMJTCpZ/crC3VQzR/kqJ4A=";

  nativeBuildInputs = [
    bun
    nodejs
    cacert
  ];

  preBuild = ''
    # Set up bun cache from pre-fetched deps (what bun2nix.hook would do)
    export BUN_INSTALL_CACHE_DIR=$(mktemp -d)
    cp -r ${bunDeps}/share/bun-cache/. "$BUN_INSTALL_CACHE_DIR"
    export HOME=$(mktemp -d)

    # bun2nix files `github:` dependencies under its own npm-style cache key,
    # but bun looks them up as `@GH@<owner>-<repo>-<shortrev>@@@1` with a
    # matching `.bun-tag`. Without this re-key bun falls back to the network,
    # which the sandbox does not have, and `bun install` hangs forever instead
    # of failing. See https://github.com/nix-community/bun2nix (github: specs).
    rekeyed=0
    for entry in "$BUN_INSTALL_CACHE_DIR"/*/*@github:*; do
      [ -e "$entry" ] || continue
      full=$(readlink -f "$entry")
      gh=$(printf '%s' "$full" | sed 's|.*@github:||')
      owner=$(printf '%s' "$gh" | cut -d/ -f1)
      repo=$(printf '%s' "$gh" | cut -d/ -f2 | cut -d'#' -f1)
      rev=$(printf '%s' "$gh" | cut -d'#' -f2)
      tag="$owner-$repo-$rev"
      target="$BUN_INSTALL_CACHE_DIR/@GH@$tag@@@1"
      mkdir -p "$target"
      cp -r "$entry"/. "$target"/
      chmod -R +w "$target"
      printf '%s' "$tag" > "$target/.bun-tag"
      echo "re-keyed bun cache entry -> @GH@$tag@@@1"
      rekeyed=$((rekeyed + 1))
    done
    if grep -q '"github:' bun.lock && [ "$rekeyed" -eq 0 ]; then
      echo "ERROR: bun.lock has github: deps but none were re-keyed;" >&2
      echo "bun would hang fetching them in the sandbox." >&2
      exit 1
    fi

    # Vite+ needs a real CA bundle in this Nix build environment.
    export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt

    # Install node_modules from cache (no network needed)
    bun install --frozen-lockfile --ignore-scripts

    # Build frontend
    cd frontend && bun run build && cd ..

    # Copy into embed directory
    rm -rf internal/web/dist
    mkdir -p internal/web
    cp -r frontend/dist internal/web/dist
    printf 'ok\n' > internal/web/dist/stub.html

    # Build the GitHub App setup page
    cd packages/github-app-ui && bun run build && cd ../..

    # Copy into its embed directory
    rm -rf internal/githubapp/ui/dist
    mkdir -p internal/githubapp/ui
    cp -r packages/github-app-ui/dist internal/githubapp/ui/dist
    printf 'ok\n' > internal/githubapp/ui/dist/stub.html
  '';

  subPackages = [ "cmd/kenn-forge" ];
  buildFlags = [ "-trimpath" ];

  # Spins up a managed-Git helper and asserts it re-sends Basic auth after a
  # restart; the request counter stays 0 in the Nix sandbox. Environment
  # sensitive, not a packaging problem — the rest of the suite still runs.
  checkFlags = [
    "-skip=^TestBuildProviderStartupAllowsAppOnlyReadRouteButRequiresRestartForManagedGit$"
  ];

  ldflags = [
    "-s"
    "-w"
    "-X main.version=${version}"
    "-X main.commit=${src.rev}"
    "-X main.buildDate=1970-01-01T00:00:00Z"
  ];

  meta = with lib; {
    description = "Local-first maintainer console with built-in agent workspaces for GitHub, GitLab, Forgejo, and Gitea";
    homepage = "https://github.com/kenn-io/forge";
    license = licenses.elastic20;
    mainProgram = "kenn-forge";
  };
}
