# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  openconnect-sso = {
    pname = "openconnect-sso";
    version = "4430cb09aefe15108e5f3b40b94ed792fbe9548b";
    src = fetchFromGitHub ({
      owner = "vlaci";
      repo = "openconnect-sso";
      rev = "4430cb09aefe15108e5f3b40b94ed792fbe9548b";
      fetchSubmodules = false;
      sha256 = "sha256-VvhPYafFfvhp7ZlygZ0kTyczkLY/5e0ip5OElX2CwhM=";
    });
    date = "2021-12-14";
  };
}
