# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/71950949-422b-46be-8707-8b19c08c97c6";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-fb0c231a-e551-4e3e-9a11-169557b088c6".device = "/dev/disk/by-uuid/fb0c231a-e551-4e3e-9a11-169557b088c6";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/0707-D807";
    fsType = "vfat";
  };

  swapDevices = [{ device = "/dev/disk/by-uuid/2c347d4a-594c-4abd-bfe9-644e3d13b906"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
