[[profile]]
name = "algo-hq"
exec = [
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 1, move workspace to "Lenovo Group Limited L32p-30 U5114TM2"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 2, move workspace to "Lenovo Group Limited L32p-30 U5114TM2"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 3, move workspace to eDP-1",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 4, move workspace to eDP-1",
]

[[profile.output]]
search = 'eDP-1'
mode = "2256x1504"
position = '517,1440'
scale = 1.500000

[[profile.output]]
search = 'Lenovo Group Limited L32p-30 U5114TM2'
mode = "3840x2160"
position = '0,0'
scale = 1.500000


[[profile]]
name = "bergen"
exec = [
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 1, move workspace to "Hewlett Packard HP E242 CN472419MR"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 2, move workspace to "Hewlett Packard HP E242 CN472419MR"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 3, move workspace to eDP-1",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 4, move workspace to eDP-1",
]

[[profile.output]]
search = 'eDP-1'
mode = "2256x1504"
position = '1920,100'
scale = 1.500000

[[profile.output]]
search = 'Hewlett Packard HP E242 CN472419MR'
mode = "1920x1200"
position = '0,0'
scale = 1.000000


[[profile]]
name = "docked"
exec = [
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 1, move workspace to "AOC U34G2G4R3 0x00000E8B"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 2, move workspace to "AOC U34G2G4R3 0x00000E8B"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 3, move workspace to eDP-1",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 4, move workspace to eDP-1",
]

[[profile.output]]
search = 'eDP-1'
mode = "2256x1504"
position = '3440,350'
scale = 1.500000

[[profile.output]]
search = 'AOC U34G2G4R3 0x00000E8B'
mode = "3440x1440@60Hz"
position = '0,0'
scale = 1.000000


[[profile]]
name = "uio"
exec = [
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 1, move workspace to "Lenovo Group Limited E27q-20 V5HNR679"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 2, move workspace to "Lenovo Group Limited E27q-20 V5HNR679"",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 3, move workspace to eDP-1",
  "/nix/store/w3zlfq4q23bpszdhvmannzqa50vnvmgj-sway-1.9/bin/swaymsg workspace number 4, move workspace to eDP-1",
]

[[profile.output]]
search = 'eDP-1'
mode = "2256x1504"
position = '530,1440'
scale = 1.500000

[[profile.output]]
search = 'Lenovo Group Limited E27q-20 V5HNR679'
mode = "2560x1440"
position = '0,0'
scale = 1.000000


[[profile]]
name = "undocked"

[[profile.output]]
search = 'eDP-1'
mode = "2256x1504"
position = '0,0'
scale = 1.500000